[[constraint]]
  name = "github.com/ipfs/go-ipfs-api"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  branch = "master"

[[constraint]]
  name = "go.etcd.io/bbolt"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
